### PR TITLE
Added Json-format-cli commands to linting

### PR DESCRIPTION
**Pull request by mika1K**
This involve installation of json-format-cli before running linting script

> sudo npm install -g json-format-cli

### CODE REVIEW

**Comment by mika1K** [comment]
closes #11

**Comment by mika1K** [comment]
Do we need to add a step for it in github actions ?

**Comment by moufmouf** [comment]
Cool! There is something I don't like though....

It sorts all the keys alphabetically. Which make no sense to me.

I would prefer to have:

```
{
  "image": "something",
  "env": {}
}
```

Rather than:


```
{
  "env": {},
  "image": "something"
}
```

Can you find a way to change this behaviour?

Also, yes, we need to check for correct formatting in Github actions.

Thanks!

**Comment by moufmouf** [comment]
Closing this since it is replaced by #43

**Pull request closed without merging**
