### PR TITLE
Adding npm-JsonLint tool 

### LINKED ISSUE #11: Adding formatting of JSON files in CI
Just like with Jsonnet files, we should make sure all JSON files are correctly linted.

### PR DESCRIPTION
**Pull request by mika1K**
closes #11

### CODE REVIEW

**Comment by mika1K** [comment]
@moufmouf  I am letting you rewiew this little fixing ,I think we can merge seems we'r allright with linting.

**Review by moufmouf — CHANGES_REQUESTED** [review]
Excellent! Thanks a lot!
There are two additional steps missing, but we are almost there!

1- You need to add validation of the linting of JSON files to the CI (an invalid JSON file should trigger an error in the CI)
2- You need to change the README to add the installation of the json-lint tool in the [Contributing](https://github.com/thecodingmachine/deeployer#contributing) section

**Comment by mika1K** [comment]
Requested changes are commited well , We can merge I think nothing's left behind

**Review by moufmouf — APPROVED** [review]

**Comment by moufmouf** [comment]
:+1:

**Pull request merged**
